import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Header, Card, ActionCard } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>What is for dinner?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <div className={styles.contentContainer}>
        <Card food={{name:"Tacos", id:45}}/>
        <div className={styles.actionContainer}> 
        <ActionCard action="Meal Prep" link="/mealprep/89"/>
        <ActionCard action="New Meal" link="/newmeal"/>
        </div>

        </div>
      </main>

      <Footer/>

    </div>
  )
}

export default Home
